project:
  type: website

website:
  title: "Darren Rajit"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog_listing.qmd
        text: Blog 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



