---
date: last-modified
date-format: "DD MMMM, YYYY"
title: Mum's Beef Rendang 
author: Darren Rajit
format: 
    html: 
        echo: false
categories: [General, Personal, Food]
link-citations: true
reference-location: margin
cap-location: margin
bibliography: personal.bib
---

# Ingredients 

Rendang is a *dry* curry, and it's a labour of love. It's composed of a paste that you fry up (@sec-rendangpaste), an aromatic base called rempah tumis[^1] (@sec-rempahtumis), a tough cut of meat (beef chuck usually) (@sec-meat), a coconut milk / cream base (@sec-coconutmilk), with toppings and flavourings (@sec-flavourings) added towards the end to add extra depth to the dish. 

I'm presenting the recipe as provided to me by my mum, who's a wonderful cook. Over time, I've experimented with my personal tweaks here and there. ie: Substitutions, things closer to what I like, etc. Check out the footnotes for these.

[^1]: *Rempah tumis* literally means fried or sauteed spices. The goal here is to achieve something called "pecah minyak" or breaking of the oil. More on this later.

## Rendang Paste {#sec-rendangpaste}

| **Ingredient**                                        | **Amount**        |
|-------------------------------------------------------|-------------------|
| Shallots                                         | 150g              |
| Lemon Grass                                      | 150g              |
| Garlic                                           | 6 Cloves          |
| Turmeric (Fresh) [^2]                             | 100g              |
| Dried Chillies (Seeded and Soaked in Water)       | 10                |

[^2]: Fresh turmeric can be subbed out for ground turmeric at a 3:1 ratio (eg: 100g -> 30g) in powder form ([Source](https://extension.colostate.edu/topic-areas/nutrition-food-safety-health/herbs-preserving-and-using-9-335/))

## 1.2. Rempah Tumis - Dry Ingredients {#sec-rempahtumis}

| **Ingredient**                                        | **Amount**        |
|-------------------------------------------------------|-------------------|
| Cloves                                          | 6 pcs             |
| Cinnamon                                        | 3 inches          |
| Star Anise                                       | 6 pcs             |
| Black Cardamom Pods                                  | 5 pcs             |

## 1.3. Meat & Marinade {#sec-meat}
| **Ingredient**                                        | **Amount**                  |
|-------------------------------------------------------|-----------------------------|
| Beef Chuck / Knuckle                              | 1kg, in bite sized chunks   |
| Onion Powder                                      | 80g                         |
| Coriander Powder                                  | 60g                         |

## 1.4. Coconut Milk Base {#sec-coconutmilk}
| **Ingredient**                                        | **Amount**        |
|-------------------------------------------------------|-------------------|
| Thick Coconut Cream                               | 0.5L              |
| Light Coconut Milk / Santan                      | 1.0L              |

## 1.5. Toppings and Flavourings {#sec-flavourings}

| **Ingredient**                                        | **Amount**        |
|-------------------------------------------------------|-------------------|
| Fresh Turmeric^[2]                                   | 1 pcs (Shredded)  |
| Salt, Sugar, MSG and Tamarind Juice               | To Taste          |
| Kerisik                                           | 200g              |
| (Optional) Turmeric Leaves                        |                   |
| (Optional) Kaffir Lime Leaves                     |                   |


# Recipe 

::: {.callout-warning}
Be prepared for a commitment when making rendang. It's a dry curry, where you're going low and slow on a tough cut of meat until all of the liquids evaporate, going from what begins as a braise into what I'd describe more akin to a fry. I'd set aside at least 3 - 4 hours to do this. The end product is definitely worth it, especially if you're cooking in bulk. Rendang lasts quite a while, especially when frozen. 
:::

## Marinate Meat {#sec-marinatemeat}

1. Marinate your beef in your dried spices (@sec-meat), preferably overnight (or at least 2 - 3 hours beforehand)

## Prepare the Rendang Paste and Rempah Tumis {#sec-preppaste}

2. Blend(@sec-rendangpaste) together until you get a fine paste [^3]. 
3. In a cast iron skillet, dutch oven, or wok, fry the paste in oil [^4] at low-medium heat until the paste and oil splits and fragrants (Figure Placeholder) [^5].
4. Add the dry spices (@sec-rempahtumis), and fry off in the paste until fragrant. You'll know when this is done, trust your nose.  


[^3]: You want to make sure you have enough moisture for your paste to form. If you're finding trouble, make sure your solid pieces are cut down to size, and feel free to add water where necessary. 
[^4]: Malaysian cooking is rarely exact, exchewing precision for intuition. Same thing goes for my mom's instructions! For our purposes, I usually eyeball around 50 - 80mls of oil. Just enough to fry off your paste in. 
[^5]: This is known as *pecah minyak*

##  III. Add Beef 

5. Add your marinated beef as done in (@sec-marinatemeat) 



