---
date: last-modified
date-format: "DD MMMM, YYYY"
title: This One Is For the Boys.
author: Darren Rajit
format: 
    html: 
        echo: false
categories: [General, Personal]
link-citations: true
reference-location: margin
cap-location: margin
---

So, Trump has won the American election. The people have spoken, and now the think pieces are out. Where to next for the progressive project? Why are young men increasingly abandoning progressive ideals and moving rightwards? Young men are being radicalized on the internet, and we're starting to see its effects come to fruition in the real world.

Incels are now mainstream, and now my social media algorithm is a blur of brain-rot alpha male podcasts, gym motivational music set to *phonk* music, and 16 year olds telling 14 year olds that they will die virgins because their eyes are slanted the wrong way[^1].

[^1]: [Context.](https://knowyourmeme.com/editorials/guides/what-is-looksmaxxing-canthal-tilt-mewing-a10s-and-t50s-among-other-lookism-buzzwords-explained) Read at your own risk

If none of what I just said makes any sense, good. I hope it never will. But if you are going to read on, it's worth noting that you're not who I'm hoping to reach with this open letter, though I do invite you to engage.

If it does, well, this one is for you, the progressive male ally, *and* the lost incel. As someone who's been floating around both these spaces for close to a decade, I think we both can do better.

## Speak, Ally!

One of the problems I have with how we're currently engaging with young men is the *vibes* of it all. Young men are in a bit of a spot of bother. Enough has been said about employment statistics, graduation rates, and rising inequality, juxtaposed against the gender standards that patriarchy continues to exert on us. I'm speaking to the converted at this point. What I want to focus on, is how we both talk *about*, and talk *to* men.

As a young man, you are constantly bombarded with negative messaging about your gender, and how you play a part in perpetuating the latest *bad* thing in the world. Everyone is talking *about* you, the *problem,* but who is talking *to* you?

Look around, and it's the Andrew Tates of the world, the Joe Rogans, the Jordan Petersons, the Steve Walshes, and the Nick Fuentes'. What are they selling? Easy solutions that reinforce the status quo, promising you everything that you *think* you should care about.

What solutions you ask? Welp firstly, it's *wokeness* that's the root of your problems. It's those damn feminists and their sycophant *soyboys*[^2]. Its *their* fault you're not getting laid, and you're not doing well at school, or earning enough money, or the fact that you have crippling depression and zero self-esteem. And you know what? Fuck 'em. Buy my course, and do everything I say, including investing in my crypto project that's definitely not a pump n' dump (lol). Oh, and also, vote Trump. He's going to bring us back to the good ol' days [^3] where men were men, you could buy a house on a single income, and things were so much simpler.

[^2]: Ie: The progressive male ally.

[^3]: that never existed btw

It's a compelling pitch, and it seems that as progressives wishing for a better world, we've ceded all ground to this rhetoric. I am guilty of the same. I've retreated to my progressive bubble on the internet, and joined the ranks of people silently watching this trainwreck unfurl in slow motion.

## Where Have all the Good Men Gone?

I don't want to *wokescold* here. But - I know where all the good men gone. We've gone silent. Fellas, and I'm including myself in this - we need to start *showing up.* There's a few trends that I'

##